language: java
sudo: false #faster builds
script: mvn test #somehow needed to create valid jacoco reports

jdk:
  - oraclejdk8

cache:
  directories:
    - $HOME/.m2

after_success:
    - bash <(curl -s https://codecov.io/bash) -t 5cab2e66-50ba-415e-a8a7-6cdf09673e88